### ISSUE TITLE
No GUI for crates when left clicked on

### ISSUE THREAD

**Issue by Jordan-Mianite** [nulli0n/GoldenCrates#1]
Title says it all.  I'll left click on the crates, there wont be any GUI Showing the potential wins.  Other players dont have a GUI either.  Randomly happened after a restart.

**Comment by nulli0n** [comment]
Check your protection plugins.

**Comment by Jordan-Mianite** [comment]
I checked them, I even gave the players chest-access and there was still no change.

**Comment by nulli0n** [comment]
I could not reproduce the issue. Test on a clean server.
