### ISSUE TITLE
Prefix arrow

### ISSUE THREAD

**Issue by hexagon02** [nulli0n/GoldenCrates#17]
Hi!
Very nice plugin, it is very useful and well made!
My only problem with it is about the customization of the messages: i can't find a way to change the symbol "»", which is shown in chat after the prefix i set up in config.yml.
Is there a way to change it?
Thanks in advance! ;)

**Comment by nulli0n** [comment]
In /NexEngine/ configs

**Comment by hexagon02** [comment]
thank you!
