### ISSUE TITLE
Plugin GoldenCrates v3.10.0 generated an exception while executing task 1623

### ISSUE THREAD

**Issue by ToxicPeople** [nulli0n/GoldenCrates#19]
https://sourceb.in/V1WpxkuaLJ

This in 241462 lines and I don't know what to do or what it is.

**Comment by ToxicPeople** [comment]
https://srcb.in/BI1ayndsmt

https://sourceb.in/kfjbCd67x1

**Comment by ToxicPeople** [comment]
What was the reason for closing my issue? You did not help me solve the problem, much less gave me an answer. Be a little more professional and on the other hand not so lazy. It costs you nothing to indicate a solution or as such an answer as to why that happened.

**Comment by nulli0n** [comment]
Use Spigot.
