### ISSUE TITLE
Required inventory space

### ISSUE THREAD

**Issue by jnijland** [nulli0n/GoldenCrates#24]
I thought I'd seen this in the plugin configuration a while ago, but I can't seem to find the option any more. 

Is there any way to set up a minimum amount of inventory slots for a crate? Or is this option removed?

**Comment by nulli0n** [comment]
It still checks it

**Comment by jnijland** [comment]
@nulli0n ok so where can I change the required space? Or is this not possible

**Comment by nulli0n** [comment]
It calculated automatically.
