### ISSUE TITLE
errors with /goldencrates reload

### ISSUE THREAD

**Issue by ValouProjet** [nulli0n/GoldenCrates#27]
Hello !
I have a weird problem with goldencrates + nexengine.
I have this error when i reload the plugin that makes the plugin broken.
https://pastebin.com/pUxeeA7X

Can u help me ?
Thanks a lot !
I installed it yesterday so it's the last version +
i'm in 1.16.5 (spigot)

**Comment by nulli0n** [comment]
Update PlaceholderAPI
