### ISSUE TITLE
Error running  commands as reward in crate.

### ISSUE THREAD

**Issue by FattigSpiller** [nulli0n/GoldenCrates#29]
Hi. I have my crate rewards setup to run a permissions command when they get the reward. It works for me who has the admin permission, but not when my players open the crate. They get the reward, but the command doesn't run. Does it have a problem running admin commands? They should be ran from the console, not from the player? Please help, thanks.

**Comment by Angelo753** [comment]
I have the same problem, will be nice to execute commands as console.

**Comment by nulli0n** [comment]
There are command tips in chat

**Comment by mav2020** [comment]
Add [CONSOLE] in front of the command like the tips say in chat when you are typing in the command (also shows %player%, etc).

**Comment by Angelo753** [comment]
Yep, I didn't noticed it, sorry for that.
