### ISSUE TITLE
CMI Hologram Support

### ISSUE THREAD

**Issue by mooshlandia** [nulli0n/GoldenCrates#31]
Hi, I noticed that the crate hologram feature requires the Holographic Displays plugin to work. Is there any chance you could add support for CMI? Thank you.

**Comment by davidotno** [comment]
This would be a nice feature, especially since cmi allows you to place items in holograms.

**Comment by nulli0n** [comment]
Won't be added. CMI API is poorly made. HD is better and a lot more stable.

**Comment by Chiquis2005** [comment]
> Won't be added. CMI API is poorly made. HD is better and a lot more stable.

you should think about it a little bit more, because even if you don't believe it there are many creators that use cmi, if you add a cmi compatibility you can expand your audience a lot, this is just my humble opinion.
