### ISSUE TITLE
keys.tmp

### ISSUE THREAD

**Issue by hexagon02** [nulli0n/GoldenCrates#34]
Hi!
Today the plugin Golden Crates stopped from giving offline players the virtual keys that I give them with the command /crates givekey <player> <key> <number>. These keys are stored (like listed) in a file called "keys.tmp". Instead, when players are online, the plugin gives them the keys correctly.
How can I fix this issue?
Thank you very much in advance!

**Comment by nulli0n** [comment]
You mean they don't receive their offline keys when joined the server?

**Comment by hexagon02** [comment]
No, they don't.
It always worked like this: i give them the keys when they are offline and they receive them even if they are online in that moment (if I use /crates checkey <player> it shows me that they received it while they were offline).
Then appeared this keys.tmp file and the problems with it.
What should this file be?

**Comment by nulli0n** [comment]
This only worked for virtual keys. For 'real' keys it always stored in that file and give them on join.
