### ISSUE TITLE
luck perms compatibility

### ISSUE THREAD

**Issue by wgruber401** [nulli0n/GoldenCrates#36]
it seems like the plugin is not compatible with luck perms when I have a crate give permission using the luck perms command lp user <user> permission set <permission> it doesn't allow the command to be run with non ops.

**Comment by wgruber401** [comment]
is there a way to force the crate to run a command from the console

**Comment by nulli0n** [comment]
See tips in chat when adding commands

**Comment by wgruber401** [comment]
thank you! I can't believe I didn't see that. Also for some reason, every player and op needs to go in creative to view a crate however once they go in creative at least once they can then view the crates until they leave the server.

**Comment by nulli0n** [comment]
check WG flags or something
