### ISSUE TITLE
Chests with permissions doesn't show up in luckperms

### ISSUE THREAD

**Issue by jobyCZ** [nulli0n/GoldenCrates#39]
I recently got a server and wanted to add some VIP chests so i made new chest and turned on the permisions, went to luckyperms editor and could not find it. I tried to reset the server but it still didn't help.
Thanks for every answer

**Comment by nulli0n** [comment]
It's not suoppsed to be showed in luckperms

**Comment by jobyCZ** [comment]
Oh. So where can i find it so i can link it to the VIP ?

**Comment by nulli0n** [comment]
right on that button in the editor

**Comment by jobyCZ** [comment]
And how do i give player the prms ?

**Comment by nulli0n** [comment]
Via permission plugin.
