### ISSUE TITLE
Givekey replaces first slot item

### ISSUE THREAD

**Issue by chamo572** [nulli0n/GoldenCrates#4]
Hi, in my server i have a bug.
I have the "Superbvote" plugin and the "nuvotifier" to create a voting / award system on the server, the problem is that when someone votes the plugin executes the command "/ crates givekey (player) (key) (amount)"  but when they receive the key, the keys replace the item they have in slot 1 of the hotbar, that is, the keys always appear there, the truth is, I don't know if the bug will be from this plugin or from the voting one, thanks

**Comment by nulli0n** [comment]
Not a GoldenCrates issue.
