### ISSUE TITLE
Title Glitch (Title always stays)

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [nulli0n/GoldenCrates#43]
Hello,
Whenever I use the editor (/crates editor --> Crate Manager --> *crate name* --> *any action that requires typing info into chat*) and complete the action, the tile "Done!" stays on my screen forever. I can remove it by doing /title @a title {"text":""}.

Server Version: Spigot 1.16.5
Plugin Version: 3.11.0

**Comment by nulli0n** [comment]
use both jar

**Comment by MinecraftMan1013number2** [comment]
> use both jar

Do you mean the NexEngine and GoldenCrates?
I already have both put into the plugins folder, and they both load successfully.

**Comment by nulli0n** [comment]
try to reset /lang/ folder in NexEngine
