### ISSUE TITLE
Issues with %goldencrates_keys_<key>% placeholder

### ISSUE THREAD

**Issue by RomainFrost** [nulli0n/GoldenCrates#45]
Hello,

As said in the title, I have issues with the %goldencrates_keys_<key>% placeholder on my server. It work for my first key, but then it doesn't work at all for every other keys (displays %goldencrates_keys_build% instead of the number of build keys). Placeholderapi is working fine with every others plugins.

Romain

**Comment by nulli0n** [comment]
Make sure key config file names does not contains spaces and such.
