### ISSUE TITLE
Tab completions are exposing vanished players

### ISSUE THREAD

**Issue by piotrskibapl** [nulli0n/GoldenCrates#47]
Hi,

The following commands are exposing vanished players:
/crate keys [username]
/crate checkkey [username]

Reproduction steps:
1. Join the server and enable vanish
2. Join the server from a second account, without permissions to see vanished players
3. Type "/crate keys " and start typing vanished player name
Observed: vanished player is present in the tab completions

**Comment by nulli0n** [comment]
It's correct because you gave the permission to run this command towards other players.
