### ISSUE TITLE
Names not showing up

### ISSUE THREAD

**Issue by trafoziya** [nulli0n/GoldenCrates#48]
I created bunch of crates a while ago. At first plugin was working great and i didnt spot any problem at all. But in last few weeks, crate names was just not there. Example: If i set a Barrel for the item of the crate, crates name was 'Barrel'. Not the name i that set up for it

**Comment by nulli0n** [comment]
You have to change crate item name too, crate name and crate item name is not the same thing.

**Comment by trafoziya** [comment]
Thanks, that solved the problem
