### ISSUE TITLE
Reward not given but message shows player receiving rewards. this is from the scratch nothing is changes..

### ISSUE THREAD

**Issue by amirshah2935** [nulli0n/GoldenCrates#60]
i try the virtual chest..with virutal key, its rolls perfectly but wehen the time to get the item it will not give..sometimes oka..sometime not..even set with 100%..
![image](https://user-images.githubusercontent.com/38003845/119225071-3eb9f580-bb34-11eb-9eab-7efb3c227eea.png)

**Comment by amirshah2935** [comment]
i already confirm its due to the template...except roll_forward and default

**Comment by nulli0n** [comment]
Which one?

**Comment by amirshah2935** [comment]
@nulli0n its is all template **except roll_forward and default** that is working..the others will give rewards with if u are lucky..we tried 18 keys only 2 or 3 reward is receives other is as above image..chech the last chat that is broadcast..it says got the reward(s): <empty> shoudl have reward name here....

**Comment by amirshah2935** [comment]
im not sure if you want to fix it since its just the template ..but others is is working and im so happy with it....so im just gonna close this..
