### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DeOpping** [nulli0n/GoldenCrates#65]
Not sure if this is the right place for suggestions, but I think it would be great if there was a way to mass-open keys maybe by _**shift+right-click**_, and it would be pretty cool if the plugin could support minecraft 1.8-1.16, a server I am Developer on is on 1.12.2 and that prevents us from using this plugin and there are like no other GOOD crate plugins!

If there is an easier way to get in contact with you that would be great, but my discord is Mantice#5760 since I don't think I'll be able to check back here easily.

**Comment by nulli0n** [comment]
No

**Comment by DeOpping** [comment]
So you can't make a mass-open feature?

**Comment by DeOpping** [comment]
Or add support for older versions?
