### ISSUE TITLE
Reward commands are executed by the player

### ISSUE THREAD

**Issue by Aearost** [nulli0n/GoldenCrates#7]
If the player gets a reward item that is to execute a command, for example a command to give the player money, they need access to said command to use it. This makes these commands useless, as they will not work unless you give them administrative permissions.

**Comment by nulli0n** [comment]
Maybe read the editor tips.

**Comment by Aearost** [comment]
Ah, found it! I would recommend making it default to being executed by console, unless specified otherwise. I don't quite see a use to a command executing from the player, considering these are executed as rewards and if they have the permission to execute the command themselves, there's no need to have this as a reward.
