### ISSUE TITLE
problem 1.16.5

### ISSUE THREAD

**Issue by CRAFTINGHARD1234** [nulli0n/GoldenCrates#82]
i download the 

3.11.0 | Mar 18, 2021

why it not working i am spigot 1.16.5 and made a server of 1.16.5 but the plugin is not working

================== NexEngine ==================
A new, better and optimized version of the Core plugin.
This Engine is required for the plugin to run.
Don't forget to check engine settings in /plugins/NexEngine/ folder.

Please, ALWAYS replace the engine .jar from every plugin update.
Remove 'FogusCore.jar' from your /plugins/ folder if you have it - it's an outdated version of this engine.
Also, rename 'FogusCore' folder to 'NexEngine' to keep the core settings.

Source: https://github.com/nulli0n/NexEngine
Feel free to use it in your projects.
===============================================

**Comment by nulli0n** [comment]
i don't know

**Comment by 100petr** [comment]
what version of java do you have? send log.

**Comment by Klmar** [comment]
Nex Engine Only Works İn Java 16 So You Have To Download JDK 16
